### PR TITLE
63 refactoring and fixes

### PR DESCRIPTION
**Pull request by Larsj02**
Done:
- Fixed a bug that cause the Main Frame to not work when inside a raid.
- Added Localization (de, it and en available)
- refactored most of the addon to use the new base lib for easier debugging and less performance impact on events.
- Fixed M+ Count appearing in tooltips outside of M+
- Added filtering to Combat log events to stop spam
- Added EventTrace DevPrint
- Fixed Event callbacks in Base Addon Mixin
- Fixed Main UI not showing Data
- Added Combat Log Data to Event Callbacks
- Added CallbackHandler as it is required for Minimap icon
- Automatically replace GetLocale() when editing a localization
- Moved Build Type to TOC so now Build Type + Version can be changed there
- Added debug logging to Saved Variables for dev mode

TODO:
- Dungeon Timer Fix for Best Times
- Adding Init Function for each file
- Changing RasuGUI to be able to apply custom Styles
- Adding InitElement function for RasuGUI to make stuff shorter that repeats like size, points, mixing tables and setting frame strata
- More RasuGUI Widgets (Textures, Texts, Secure/Insecure Button, Dropdown)
- More RasuGUI Base Mixin functionality (MakeClickable())
- Features to change the apperance of the M+ timer
- Fix so the M+ timer with the current bugs that are present.
- Give M+ score calculator more muscle.
- Fix main frame Tooltip/Keystone and Level

### CODE REVIEW

**Comment by Thekinghim** [comment]
https://github.com/Thekinghim/keystone-companion/assets/151988881/f853c00c-7f49-45eb-b2a7-ff4f6c86e520

Not sure why its still buggy. It does not show the portals sometimes and the tooltip is no where to be seen.

**Comment by Thekinghim** [comment]
https://gyazo.com/aceef444e1f2162f5f4f889fc72d219d

**Comment by Thekinghim** [comment]
The text in the timer is still overlappaning and there is text showing under the text see screenshot ^^

**Review by Thekinghim — APPROVED** [review]

**Comment by Larsj02** [comment]
> 2024-05-07.06-05-41.mp4 
> Not sure why its still buggy. It does not show the portals sometimes and the tooltip is no where to be seen.

I mean this is working like before and works exactly like it should no ? 
The Priest either doesn't have a key or he doesn't have our Addon or Details so we can't get his Key Info.
For the Paladin after reload it took a bit cause the Addon is making requests and waiting for an Answer for updating when people just go offline it would also not show keys as they can't answer

**Pull request merged**
